/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Aleim
 */
public class frmInformacionCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmInformacionCliente
     */
    public frmInformacionCliente() {
        initComponents();
        
        try {
            Font poppins = Font.createFont(Font.TRUETYPE_FONT, new File("src/Fonts/Poppins/Poppins-regular.ttf"));
            Font comboBox = poppins;
            poppins = poppins.deriveFont(16f); 
            comboBox = comboBox.deriveFont(14f); 
            
            txtNombreCliente.setFont(poppins);
            txtApellidosCliente.setFont(poppins);
            txtCorreoCliente.setFont(poppins);
            txtDUIcliente.setFont(poppins);
            cbMesero.setFont(comboBox);
            btnListo.setFont(poppins);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtDUIcliente = new javax.swing.JTextField();
        cbMesero = new javax.swing.JComboBox<>();
        btnListo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 620));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setToolTipText("Nombre del cliente");
        txtNombreCliente.setBorder(null);
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 202, 210, 30));

        txtApellidosCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidosCliente.setToolTipText("Apellidos del cliente");
        txtApellidosCliente.setBorder(null);
        jPanel1.add(txtApellidosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 279, 210, 30));

        txtCorreoCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoCliente.setToolTipText("Correo eletrónico del cliente");
        txtCorreoCliente.setBorder(null);
        jPanel1.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 350, 210, 30));

        txtDUIcliente.setForeground(new java.awt.Color(0, 0, 0));
        txtDUIcliente.setToolTipText("DUI del cliente");
        txtDUIcliente.setBorder(null);
        jPanel1.add(txtDUIcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 420, 210, 30));

        cbMesero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbMesero.setToolTipText("Seleccione un mesero encargado");
        jPanel1.add(cbMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 484, 110, 30));

        btnListo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnListo.setForeground(new java.awt.Color(0, 0, 0));
        btnListo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListo.setText("   Listo");
        btnListo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 542, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/infoCliente_img.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInformacionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnListo;
    public javax.swing.JComboBox<String> cbMesero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtApellidosCliente;
    public javax.swing.JTextField txtCorreoCliente;
    public javax.swing.JTextField txtDUIcliente;
    public javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
