/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import static Vista.frmLogin.initFrmLogin;

/**
 *
 * @author Aleim
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        btnMenuInicio.enable(false);
        pnlMainContainer.setVisible(false);
    }

    public static void initFrmMenu()
    {
     frmMenu menu = new frmMenu();
     menu.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMainContainer = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JLabel();
        btnMesasOcupadas = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlMainContainerLayout = new javax.swing.GroupLayout(pnlMainContainer);
        pnlMainContainer.setLayout(pnlMainContainerLayout);
        pnlMainContainerLayout.setHorizontalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        pnlMainContainerLayout.setVerticalGroup(
            pnlMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        jPanel1.add(pnlMainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1250, 770));

        btnMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon.png"))); // NOI18N
        btnMenuInicio.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_icon_selected.png"))); // NOI18N
        btnMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuInicioMouseClicked(evt);
            }
        });
        jPanel1.add(btnMenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 40, -1, 70));

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_icon.png"))); // NOI18N
        btnAgregarCliente.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_icon_selected.png"))); // NOI18N
        btnAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 160, -1, 70));

        btnMesasOcupadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Table_icon.png"))); // NOI18N
        btnMesasOcupadas.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Table_icon_selected.png"))); // NOI18N
        jPanel1.add(btnMesasOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 300, -1, 70));

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_icon.png"))); // NOI18N
        btnPerfil.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User_icon_selected.png"))); // NOI18N
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 420, -1, 70));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogOut_icon.png"))); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 660, -1, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu_img.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        initFrmLogin();
        this.dispose();
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarClienteMouseClicked
        pnlRegistrarClientes clientes = new pnlRegistrarClientes();       
        pnlMainContainer.removeAll();
        pnlMainContainer.add(clientes);
        pnlMainContainer.repaint();
        pnlMainContainer.revalidate();
        pnlMainContainer.setVisible(true);
    }//GEN-LAST:event_btnAgregarClienteMouseClicked

    private void btnMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuInicioMouseClicked
        pnlMainContainer.setVisible(false);
    }//GEN-LAST:event_btnMenuInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregarCliente;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnMenuInicio;
    private javax.swing.JLabel btnMesasOcupadas;
    private javax.swing.JLabel btnPerfil;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlMainContainer;
    // End of variables declaration//GEN-END:variables
}
