package Vista;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;

public class pnlPerfil extends javax.swing.JPanel {

    /**
     * Creates new form pnlPerfil
     */
    public pnlPerfil() {
        initComponents();
        try {
            Font poppinsFont = Font.createFont(Font.TRUETYPE_FONT, new File("src/Fonts/Poppins/Poppins-Regular.ttf"));
            poppinsFont = poppinsFont.deriveFont(15f); 
            txtCorreoPerfil.setFont(poppinsFont);
            txtDUIperfil.setFont(poppinsFont);
            txtTelefonoPerfil.setFont(poppinsFont);
            lblNombreEmpleado.setFont(poppinsFont);
            lblApellidosEmpleado.setFont(poppinsFont);
            lblCargoEmpleado.setFont(poppinsFont);
            btnCerrarSesion.setFont(poppinsFont);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelefonoPerfil = new javax.swing.JTextField();
        txtCorreoPerfil = new javax.swing.JTextField();
        txtDUIperfil = new javax.swing.JTextField();
        btnCerrarSesion = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblApellidosEmpleado = new javax.swing.JLabel();
        lblCargoEmpleado = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefonoPerfil.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoPerfil.setToolTipText("Ingrese su nombre de usuario");
        txtTelefonoPerfil.setBorder(null);
        jPanel1.add(txtTelefonoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 491, 290, 40));

        txtCorreoPerfil.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoPerfil.setToolTipText("Ingrese su nombre de usuario");
        txtCorreoPerfil.setBorder(null);
        jPanel1.add(txtCorreoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 285, 290, 40));

        txtDUIperfil.setForeground(new java.awt.Color(0, 0, 0));
        txtDUIperfil.setToolTipText("Ingrese su nombre de usuario");
        txtDUIperfil.setBorder(null);
        jPanel1.add(txtDUIperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 388, 290, 40));

        btnCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setText("Cerrar Sesión");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 380, 80));

        lblNombreEmpleado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNombreEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreEmpleado.setText("Nombre del empleado");
        jPanel1.add(lblNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 410, 50));

        lblApellidosEmpleado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblApellidosEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidosEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApellidosEmpleado.setText("Apellidos del empleado");
        jPanel1.add(lblApellidosEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 410, 50));

        lblCargoEmpleado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCargoEmpleado.setForeground(new java.awt.Color(255, 0, 0));
        lblCargoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargoEmpleado.setText("Cargo del empleado");
        jPanel1.add(lblCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 690, 410, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Perfil_img.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidosEmpleado;
    private javax.swing.JLabel lblCargoEmpleado;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JTextField txtCorreoPerfil;
    private javax.swing.JTextField txtDUIperfil;
    private javax.swing.JTextField txtTelefonoPerfil;
    // End of variables declaration//GEN-END:variables
}
