package Vista;

public class pnlRegistrarClientes extends javax.swing.JPanel {

    /**
     * Creates new form pnlRegistrarClientes
     */
    public pnlRegistrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Mesa1 = new javax.swing.JLabel();
        Mesa2 = new javax.swing.JLabel();
        Mesa3 = new javax.swing.JLabel();
        Mesa4 = new javax.swing.JLabel();
        Mesa5 = new javax.swing.JLabel();
        Mesa6 = new javax.swing.JLabel();
        Mesa7 = new javax.swing.JLabel();
        Mesa8 = new javax.swing.JLabel();
        Mesa9 = new javax.swing.JLabel();
        Mesa10 = new javax.swing.JLabel();
        Mesa11 = new javax.swing.JLabel();
        Mesa12 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 70, 70));

        Mesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 70, 70));

        Mesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 70, 70));

        Mesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 70, 70));

        Mesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 70, 70));

        Mesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 70, 70));

        Mesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 70, 70));

        Mesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 70, 70));

        Mesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 600, 70, 70));

        Mesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 603, 70, 70));

        Mesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 70, 70));

        Mesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_disponible.png"))); // NOI18N
        Mesa12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_ocupado.png"))); // NOI18N
        jPanel1.add(Mesa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 70, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Croquis_img.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Mesa1;
    public javax.swing.JLabel Mesa10;
    public javax.swing.JLabel Mesa11;
    public javax.swing.JLabel Mesa12;
    public javax.swing.JLabel Mesa2;
    public javax.swing.JLabel Mesa3;
    public javax.swing.JLabel Mesa4;
    public javax.swing.JLabel Mesa5;
    public javax.swing.JLabel Mesa6;
    public javax.swing.JLabel Mesa7;
    public javax.swing.JLabel Mesa8;
    public javax.swing.JLabel Mesa9;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
